services:
  anyconnect:
    restart: always
    image: anyconnectproxy:latest
    container_name: anyconnectproxy
    env_file:
      - dev.env
    ports:
      - "9052:9052"
    build:
      context: .
      dockerfile: Dockerfile
    ## Pass in usb devices if needed for MFA
    # devices:
    #   - /dev/bus/usb:/dev/bus/usb 
    #   - /dev/usb:/dev/usb
    #   - /dev/net/tun:/dev/net/tun